---
title: Let simulation be a substitute for thinking
author: R package build
date: '2021-03-23'
slug: let-simulation-be-a-substitute-for-thinking
categories: []
tags: []
---

My mother is a keen reader of 'the daily scienctist', a UK based popular sceince magazine. Invariably over a given weenend she'll exclaim something along the lines of "The last estimate was wrong, the obserable universe is 245,600,00 years old, not 245,700,00" or "carrots have been proven to make you totally immune to cancer", ill take an interest but quickly return to my book (/phone). 

so here it is


"Dog breeder Harriet Hound’s prize pooch has just had 10 puppies. She is particularly pleased, because there are only nine puppies in the latest litter of her arch-rival, Matilda Mutt.

However, for Harriet, it isn’t just the overall quantity that counts, it is the number of female puppies, because females earn her a premium. On average, 50 per cent of puppies are female. “What is the chance I’ve got more female puppies than Matilda?” wonders Harriet.

You might think she needs to use sophisticated probability maths to work this out, but in fact there is a way to figure out the solution with some relatively simple reasoning."


