---
title: Consider blogging
author: R package build
date: '2021-03-23'
slug: consider-blogging
categories: []
tags: []
draft: true
---
 
:boom:

I think good data scientist should consider blogging
Lets cut to the chase here, in no particular order these are the skills that blogging will help you with.

- ordering your thoughts

- finishing things.

- Communicating results to a non-technical audience. 

- practicing reproducibilty

-incentive to stay curious. I'm more likely to go that extra mile to check out an interesting sounding package if i think it could be the makings of an interesting blog post. 

- Getting your name out there. If you know stuff, and you want other to know that you know stuff. Then you have two options 
a) constantly remind people how much you know by not so subtly hijack conversations to make that abundantly clear to everyone
b) Have a workbook of code/ blog where you can show evidence of things that you do and dont know, and allow anyone to browse  at thier own leasure.

i'm sure you'll make the right choice

- Web developement. I see making a blog as my first, very tentative, exploration into the world of webdevelopment. I hope at the very least it will keep HTML and CSS fresh in my mind and think about how a website might be structured. There are lots of technologies involved in building websites, exposure to a few surely is no bad thing. Knowing the difference between a static and dynamic website, the file structure of a simple website