---
title: "Ezra Citron"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


+447960085010   ~   31 Cheyne Walk, London, NW4 3QH   ~   ezracitron@gmail.com
 
 *** 
 
 
## Education
Christ’s College, University of Cambridge - Economics Adv. Dip
Sept 2018- July 2019
Modules include: Monetary and International Macroeconomics, Game Theory, Advanced Econometrics I & II


King’s College London- BSc Mathematics                                                              
Sept 2015 - 2018  
1st Class Honours (75% avg.)
Modules include: Financial Mathematics, Probability & Statistics, Linear Models & Regression Analysis

Hasmonean High School 
2007 - 2014
A Level:   Mathematics (A*)  Further Mathematics (A*)   Physics (A)  
GCSE:   5 A* ,  5 A  

Experience
HSBC - Data Science - Canary Wharf, London
Oct 2019 - Oct 2021

Skills Used:

R: dplyr, ggplot, NLP ,  Python - SkiLearn, Github

Lead a machine learning to project to predict outcomes of new joiners based on features of their application. This modeling was used to fine tune the application process and gain insight into 

Part of a team responsible for gaining insight from the global HSBC-wide survey. NLP used on verbatim comments to extract insight. Binary clustering used to pool monitor employee experience.  

Statistical testing on misconduct data to assess for bias.

Networki Analysis. and visualisation

Natural Language processing. PCC cases. 

Re-Engineered the processes used to model the global bonus pool. My scripted manual processes and streamlined SQL script that ran overnight, to R code that ran in under 5 minutes. 

experience building an interactive shiny web application

Zurich Insurance
July - September 2018

I worked as part of the data team within the Brexit project, which was responsible for managing the risks and gaining regulatory approval for the company’s post-brexit restructuring. Specifically, I was tasked with understanding the flow of data within Zurich UK in order to justify to the PRA that our processes were well managed. I documented the flow of data; how the granular customer data is stored and then manipulated it in order to calculate the final risk parameters. My work was focused on credit risk and expense risk. I received positive feedback for the clarity of my writing and the speed with which I understood the models. 

AIG (American International Group) - Enterprise Risk Management (ERM) - Fenchurch St, London
June - Sept 2017

I was selected for a competitive 10 week summer internship which included rotations within the Capital Modelling and Risk Framework teams. I communicated in-depth technical risk analysis to major stakeholders and met regularly with the Senior Managing Director to report on balancing profitability, growth and risk. I worked on calculating the solvency capital requirement (SCR) using the firm’s internal modeling software; this required high levels of quantitative and critical thinking. I also gained a strong introduction to econometric modelling, stochastic methods and computer programming.
Projects:
Delivered an hour presentation entitled “Risk Benchmarking between Global Insurance Firms”,  to senior management - including the CRO. Topics included: Credit risk, Market risk and Operational risk. My manager gave positive feedback on my dynamic delivery and well-reasoned responses to questions.
Led a project to overhaul and improve the ERM webpage of AIG Europe. I re-engineered the content and formatting using input from colleagues.
Conducted a research project on the emerging risks within the insurance sector. Particular emphasis was given to topics such as Cyber risk, Brexit and Political instability.
Collaborated with Management Consulting firm ‘Oliver Wyman’ on an industry-wide Benchmarking exercise. I consulted with other departments to collate and organise firm-wide data. This exhibits my ability to work in a team to execute goals.
I was offered a full-time graduate role.

President of Society - King’s College London 
Sept 2016 - June 2017                                                                 
Represented 300+ Jewish students on campus and organised regular events and lunches for up to 150 students.
Led a team of 6. 
Responsibilities included: attracting external speakers, financial management, event planning and social media.
Transformed the society's social media strategy, leading to a ~30% increase in attendance.
Generated revenues of over £3000 via 3 main London-wide university events. 

Hobbies, Interests and Achievements 
College Rowing - I trained 9 times per week as part of the first team of Christ’s College boat club (CCBC). I competed in the annual college wide boat race, known as ‘Bumps’.
Running - Ran half marathon events in several countries, raised over £2500 for charities.       
Guitar - I am an enthusiastic rock guitarist, I play in a band with my two younger brothers. 
